### PR TITLE
Implement feature of showing file uploading progress in get_file_info

### PR DESCRIPTION
**Pull request by tanzhanwen**
This change is [Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/122)

### CODE REVIEW

**Review by qhz-ty — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/122)* status: all files reviewed, 1 unresolved discussion (waiting on @tanzhanwen)

___
*[`node/chunk_pool/src/mem_pool/chunk_cache.rs` line 148 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/122#-NDC03uCCbyvYrhTM_DO:-NDC03uCCbyvYrhTM_DP:b23yii6) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/3d25aaa693f5b9bebeca691082229755b634d015/node/chunk_pool/src/mem_pool/chunk_cache.rs#L148)):*
> ```XML
>         };
> 
>         cached_seg_num
> ```

Could return in `match` body directly.

**Review by qhz-ty — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tanzhanwen)

**Review by tanzhanwen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/122)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @qhz-ty)

___
*[`node/chunk_pool/src/mem_pool/chunk_cache.rs` line 148 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/122#-NDC03uCCbyvYrhTM_DO:-NE3byeN6kt5iiiPfMiE:bb6un1j) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/3d25aaa693f5b9bebeca691082229755b634d015/node/chunk_pool/src/mem_pool/chunk_cache.rs#L148)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

Could return in `match` body directly.
</blockquote></details>

Done

**Review by qhz-ty — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tanzhanwen)

**Pull request merged**
