### PR TITLE
Support to sync file among all peers automatically

### PR DESCRIPTION
**Pull request by qhz-ty**
This change is [Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/93)

### CODE REVIEW

**Review by zz-ionian — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/93)* status: all files reviewed, 1 unresolved discussion (waiting on @cxlup and @qhz-ty)

___
*[`node/storage/src/log_store/log_manager.rs` line 253 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/93#-NBCFe_O50eRIv2hiMbH:-NBCFe_O50eRIv2hiMbI:bra6bj2) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/335e283eb8610b432b8bb64e517af8b2adb152e4/node/storage/src/log_store/log_manager.rs#L253)):*
> ```XML
> 
> impl Configurable for LogManager {
>     fn get_config(&self, key: &[u8]) -> Result<Option<Vec<u8>>> {
> ```

We can probably define this as `get_config<T>(...) -> Result<Option<T>> where T: Decode` (also `set_config`) to wrap the encoding/decoding within the trait?

**Review by qhz-ty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/93)* status: all files reviewed, 1 unresolved discussion (waiting on @cxlup and @zz-ionian)

___
*[`node/storage/src/log_store/log_manager.rs` line 253 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/93#-NBCFe_O50eRIv2hiMbH:-NBFVm0e9WIyRAjtOZI1:by5dhnp) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/335e283eb8610b432b8bb64e517af8b2adb152e4/node/storage/src/log_store/log_manager.rs#L253)):*
<details><summary><i>Previously, zz-ionian wrote…</i></summary><blockquote>

We can probably define this as `get_config<T>(...) -> Result<Option<T>> where T: Decode` (also `set_config`) to wrap the encoding/decoding within the trait?
</blockquote></details>

Totally agree, but the compilation will be failed if define generic methods in a trait, which is used as a `dyn` type. Do you know how to resolve such compilation failure?

**Review by zz-ionian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cxlup)

**Review by zz-ionian — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cxlup)

**Pull request merged**
