### PR TITLE
Implement feature of caching small file when log entry is not available

### PR DESCRIPTION
**Pull request by tanzhanwen**
This change is [Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109)

### CODE REVIEW

**Review by qhz-ty — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109)* status: all files reviewed, 5 unresolved discussions (waiting on @tanzhanwen)

___
*[`node/chunk_pool/src/mem_pool/chunk_cache.rs` line 13 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwpvIb7hwTaxABGi8C:-NCwpvIcAkFLzBrqyCmm:b-pac96r) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_cache.rs#L13)):*
> ```XML
> pub struct MemoryCachedFile {
>     /// Window to control the cache of each file
>     pub segments: Option<HashMap<usize, ChunkArray>>,
> ```

`Option` is unnecessary if this is to cache small file.



_Code quote:_
```XML
Option
```
___
*[`node/chunk_pool/src/mem_pool/chunk_pool_inner.rs` line 119 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwsLjl50iRwMeNHOZS:-NCwsLjl50iRwMeNHOZT:bjfzpsa) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_pool_inner.rs#L119)):*
> ```XML
>         seg_index: usize,
>         info: SegmentMetaInfo,
>     ) -> Result<()> {
> ```

How about to split into 2 methods, one for normal file and the other for small file? E.g. `cache_segment` vs. `write_segment`.
___
*[`node/chunk_pool/src/mem_pool/chunk_pool_inner.rs` line 134 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwrk2pDoPlbPjQoWMN:-NCwrk2pDoPlbPjQoWMO:b-q4syur) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_pool_inner.rs#L134)):*
> ```XML
>             )?;
>             inner.segment_cache.update_expiration_time(&root);
>             drop(inner);
> ```

Strongly recommend not to `drop` an object explicitly.
___
*[`node/chunk_pool/src/mem_pool/chunk_pool_inner.rs` line 185 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwsimF7AiBiFtGK2TN:-NCwsimG-gFsPQiJybPH:bt5rd3w) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_pool_inner.rs#L185)):*
> ```XML
>             max_writings,
>         )?;
>         drop(inner);
> ```

Again, do not drop by yourself, could use code block instead.
___
*[`node/log_entry_sync/src/sync_manager/mod.rs` line 26 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwna_Z111HF0j_urw5:-NCwna_Z111HF0j_urw6:bdg0kxd) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/log_entry_sync/src/sync_manager/mod.rs#L26)):*
> ```XML
>     log_fetcher: LogEntryFetcher,
>     store: Arc<RwLock<dyn Store>>,
>     chunk_pool: Arc<MemoryChunkPool>,
> ```

How about to use `broadcast` or event based mechanism to decouple with the `ChunkPool`, and also allow other modules to aware the log entry event?

**Review by tanzhanwen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109)* status: all files reviewed, 5 unresolved discussions (waiting on @qhz-ty)

___
*[`node/chunk_pool/src/mem_pool/chunk_cache.rs` line 13 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwpvIb7hwTaxABGi8C:-ND-51Ef3tuPH8n-Xm9W:b-v6ao5c) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_cache.rs#L13)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

`Option` is unnecessary if this is to cache small file.
</blockquote></details>

Option is used here because ownership of the segments is transferred when cache is written into storage. Therefore, I use Option here so that take() method can be called to retrieve the segments in struct MemoryCachedFile. 
___
*[`node/chunk_pool/src/mem_pool/chunk_pool_inner.rs` line 119 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwsLjl50iRwMeNHOZS:-ND-5ntA-tAwt4nxjU2b:b-ucwth5) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_pool_inner.rs#L119)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

How about to split into 2 methods, one for normal file and the other for small file? E.g. `cache_segment` vs. `write_segment`.
</blockquote></details>

I am a little bit confused. I have separated these two cases into the if-else branches. If info.need_cache, then it is the case for small files, while else is the case for ordinary files. Do you mean I should further group the codes in if-else branches into two separate methods?
___
*[`node/chunk_pool/src/mem_pool/chunk_pool_inner.rs` line 134 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwrk2pDoPlbPjQoWMN:-ND-6ROS0zH9HgEAZnKu:b4v0cc8) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_pool_inner.rs#L134)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

Strongly recommend not to `drop` an object explicitly.
</blockquote></details>

Is it OK to use a code block instead? So that when the lock goes out of scope, it is dropped automatically.
___
*[`node/chunk_pool/src/mem_pool/chunk_pool_inner.rs` line 185 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwsimF7AiBiFtGK2TN:-ND-7ZlL9ZW9P5bFGfjw:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_pool_inner.rs#L185)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

Again, do not drop by yourself, could use code block instead.
</blockquote></details>

Done.
___
*[`node/log_entry_sync/src/sync_manager/mod.rs` line 26 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwna_Z111HF0j_urw5:-ND-8OKf7EFxDe53vknX:b-bshwfb) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/log_entry_sync/src/sync_manager/mod.rs#L26)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

How about to use `broadcast` or event based mechanism to decouple with the `ChunkPool`, and also allow other modules to aware the log entry event?
</blockquote></details>

Does it mean something like subscription & notification? Other modules can subscribe the event of log entry, and the event is notified to all modules that subscribe it. Is there any existing code snippet that I can refer to?

**Review by tanzhanwen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109)* status: all files reviewed, 5 unresolved discussions (waiting on @qhz-ty)

___
*[`node/chunk_pool/src/mem_pool/chunk_cache.rs` line 13 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwpvIb7hwTaxABGi8C:-ND4R3cb3U9TjeGgcvV2:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_cache.rs#L13)):*
<details><summary><i>Previously, tanzhanwen (Zane.tzw) wrote…</i></summary><blockquote>

Option is used here because ownership of the segments is transferred when cache is written into storage. Therefore, I use Option here so that take() method can be called to retrieve the segments in struct MemoryCachedFile. 
</blockquote></details>

Done.
___
*[`node/chunk_pool/src/mem_pool/chunk_pool_inner.rs` line 119 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwsLjl50iRwMeNHOZS:-ND4R9J3D4jJWDnKTbJ3:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_pool_inner.rs#L119)):*
<details><summary><i>Previously, tanzhanwen (Zane.tzw) wrote…</i></summary><blockquote>

I am a little bit confused. I have separated these two cases into the if-else branches. If info.need_cache, then it is the case for small files, while else is the case for ordinary files. Do you mean I should further group the codes in if-else branches into two separate methods?
</blockquote></details>

Done.
___
*[`node/chunk_pool/src/mem_pool/chunk_pool_inner.rs` line 134 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwrk2pDoPlbPjQoWMN:-ND4RABl7Fd8zHvjms-E:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/chunk_pool/src/mem_pool/chunk_pool_inner.rs#L134)):*
<details><summary><i>Previously, tanzhanwen (Zane.tzw) wrote…</i></summary><blockquote>

Is it OK to use a code block instead? So that when the lock goes out of scope, it is dropped automatically.
</blockquote></details>

Done.

**Review by tanzhanwen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109)* status: 7 of 16 files reviewed, 5 unresolved discussions (waiting on @qhz-ty)

___
*[`node/log_entry_sync/src/sync_manager/mod.rs` line 26 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109#-NCwna_Z111HF0j_urw5:-ND4ZWj84FlABFIo7O0n:buibsr9) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/8d8b44a981e8c01f75df284be6622d9fda052336/node/log_entry_sync/src/sync_manager/mod.rs#L26)):*
<details><summary><i>Previously, tanzhanwen (Zane.tzw) wrote…</i></summary><blockquote>

Does it mean something like subscription & notification? Other modules can subscribe the event of log entry, and the event is notified to all modules that subscribe it. Is there any existing code snippet that I can refer to?
</blockquote></details>

Rollbacked the changes. Will implement this in next PR.

**Review by qhz-ty — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tanzhanwen)

**Pull request merged**
