### PR TITLE
Add functional test framework

### PR DESCRIPTION
**Pull request by cxlup**
- Add functional test framework
- Use BSC as default blackchain
- Add example test and RPC tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60)

### CODE REVIEW

**Review by zz-ionian — CHANGES_REQUESTED** [review]
> Reviewed 13 of 20 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60)* status: 19 of 20 files reviewed, 6 unresolved discussions (waiting on @cxlup and @zz-ionian)

___
*[`node/build.rs` line 12 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FJymc90OSuKr5TVDy:-N9FJymc90OSuKr5TVDz:b9ro62f) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/node/build.rs#L12)):*
> ```XML
>     let status = Command::new("go")
>         .current_dir("../ionian-client")
>         .args(vec!["build"])
> ```

I was thinking that `ionian-client` is built in the test_framework, but this should work for now.
___
*[`tests/rpc_test.py` line 97 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FMQ5X120OJqPyltxn:-N9FMQ5X120OJqPyltxo:byr62pp) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/rpc_test.py#L97)):*
> ```Python
> 
>                 assert_equal(
>                     client1.ionian_download_segment(root, 0, 2),
> ```

I'm not sure about this... Why is `client1` defined in `run_test` available here?
___
*[`tests/config/node_config.py` line 3 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FNA2p1oSanqMqOMya:-N9FNA2p1oSanqMqOMyb:b-7xf0ti) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/config/node_config.py#L3)):*
> ```Python
> from web3 import Web3
> 
> CONFLUX_CONFIG = dict(
> ```

These can be removed for now.
___
*[`tests/node/transactions.py` line 59 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FNMv32T2sXxPnjeSE:-N9FNMv32T2sXxPnjeSF:bf9hsm0) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/node/transactions.py#L59)):*
> ```Python
> 
> 
> class UnsignedTransaction(rlp.Serializable):
> ```

This is also unused.
___
*[`tests/test_framework/blockchain_node.py` line 82 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FO-dJ5mRjKy-5KiT7:-N9FO-dJ5mRjKy-5KiT8:b-l9n6dr) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/test_framework/blockchain_node.py#L82)):*
> ```Python
>         initialize_config(self.config_file, self.config)
> 
>     def start(self, redirect_stderr=False):
> ```

Since we will check stderr when we stop a node, we should probably remove this parameter in case it's used and some errors get undetected.



_Code quote:_
```Python
redirect_stderr=False
```
___
*[`tests/test_framework/blockchain_node.py` line 234 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FOMI989WMUYsdtF5v:-N9FOMI989WMUYsdtF5w:b-d3ifll) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/test_framework/blockchain_node.py#L234)):*
> ```Python
>             bytecode=contract_interface["bytecode"]["object"],
>         )
>         account = w3.eth.account.from_key(CONFLUX_GENESIS_PRIV_KEY)
> ```

Is the private key correct for BSC nodes?
___
*[`tests/utility/utils.py` line 92 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FiAp21tbyprJ-rcTI:-N9FiAp21tbyprJ-rcTJ:b-know0t) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/utility/utils.py#L92)):*
> ```Python
> 
> 
> def initialize_conflux_config(data_dir, config_parameters):
> ```

same unused.

**Review by cxlup — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60)* status: 19 of 20 files reviewed, 6 unresolved discussions (waiting on @zz-ionian)

___
*[`tests/rpc_test.py` line 97 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FMQ5X120OJqPyltxn:-N9Fw8kw5ReF3yz0gqK_:bdpevdd) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/rpc_test.py#L97)):*
<details><summary><i>Previously, zz-ionian wrote…</i></summary><blockquote>

I'm not sure about this... Why is `client1` defined in `run_test` available here?
</blockquote></details>

Client1 is passed in via argument
___
*[`tests/config/node_config.py` line 3 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FNA2p1oSanqMqOMya:-N9FwGEe4gj7wO7hExi6:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/config/node_config.py#L3)):*
<details><summary><i>Previously, zz-ionian wrote…</i></summary><blockquote>

These can be removed for now.
</blockquote></details>

Done.
___
*[`tests/node/transactions.py` line 59 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FNMv32T2sXxPnjeSE:-N9Fx8cn8WnBbSAyYvbQ:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/node/transactions.py#L59)):*
<details><summary><i>Previously, zz-ionian wrote…</i></summary><blockquote>

This is also unused.
</blockquote></details>

Done.
___
*[`tests/test_framework/blockchain_node.py` line 82 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FO-dJ5mRjKy-5KiT7:-N9FxGCW6x23lcSOj0fx:b-shucbv) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/test_framework/blockchain_node.py#L82)):*
> we will check stderr when we stop a node, we should 
This is a limitation from bsc node, bsc node always write logs to stderr, So i redired stderr to stdout. Do you have any good suggestions?
___
*[`tests/test_framework/blockchain_node.py` line 234 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FOMI989WMUYsdtF5v:-N9FxfQC3j9VJ3-PoLNZ:bnngnyj) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/test_framework/blockchain_node.py#L234)):*
<details><summary><i>Previously, zz-ionian wrote…</i></summary><blockquote>

Is the private key correct for BSC nodes?
</blockquote></details>

Yes, I rename it to GENESIS_PRIV_KEY
___
*[`tests/utility/utils.py` line 92 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FiAp21tbyprJ-rcTI:-N9FxsnO2rLuSrN0jMeu:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/utility/utils.py#L92)):*
<details><summary><i>Previously, zz-ionian wrote…</i></summary><blockquote>

same unused.
</blockquote></details>

Done.

**Review by zz-ionian — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cxlup)

___
*[`tests/test_framework/blockchain_node.py` line 82 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60#-N9FO-dJ5mRjKy-5KiT7:-N9G19Hh1qSpHX9GIGc0:b-veign7) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ed7c840583a2dbebe0f9bcaec80c241bc5bfc5d2/tests/test_framework/blockchain_node.py#L82)):*
<details><summary><i>Previously, cxlup (csd) wrote…</i></summary><blockquote>

> we will check stderr when we stop a node, we should 
This is a limitation from bsc node, bsc node always write logs to stderr, So i redired stderr to stdout. Do you have any good suggestions?
</blockquote></details>

Ok, then let's leave it like this so far...

**Review by zz-ionian — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cxlup)

**Review by zz-ionian — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cxlup)

**Pull request merged**
