### PR TITLE
Support to auto sync file for all nodes

### PR DESCRIPTION
**Pull request by qhz-ty**
When file uploaded and finalized on storage node, it will publish `AnnounceFile` gossip message to other nodes to sync file automatically.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/56)

### CODE REVIEW

**Review by zz-ionian — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ionian-dev)

**Review by zz-ionian — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/56)* status: all files reviewed, 1 unresolved discussion (waiting on @ionian-dev and @qhz-ty)

___
*[`node/sync/src/service.rs` line 396 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/56#-N8ZTz8n0tl7eb3nWJCh:-N8ZTz8n0tl7eb3nWJCi:b-au5xgh) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/fe2f9a9e75f97849a0fb46cc5f509ed09279c8b7/node/sync/src/service.rs#L396)):*
> ```XML
> 
>         // Now, always sync files among all nodes
>         self.on_start_sync_file(tx_seq).await;
> ```

We can add the source to the known peer who has this file.

**Review by qhz-ty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/56)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ionian-dev and @zz-ionian)

___
*[`node/sync/src/service.rs` line 396 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/56#-N8ZTz8n0tl7eb3nWJCh:-N8afMI20FuW0qJec_Iy:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/fe2f9a9e75f97849a0fb46cc5f509ed09279c8b7/node/sync/src/service.rs#L396)):*
<details><summary><i>Previously, zz-ionian wrote…</i></summary><blockquote>

We can add the source to the known peer who has this file.
</blockquote></details>

Done.

**Review by zz-ionian — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ionian-dev)

**Pull request merged**
