### PR TITLE
Implement flow-based storage.

### PR DESCRIPTION
**Pull request by zz-ionian**
Note that the project does not compile. This only makes the two crates `storage` and `append_merkle` compilable.

TODO: 
- [x] Allow the Merkle root to be computed based on the transaction Merkle root list when the tx data are missing.
- [x] Implement interfaces of `LogManager`  for the upper layers.
- [x]  Sync new contract logs and update LogManager accordingly. (Wait for new contract implementation)

Data seal/unseal and other mining-related operations will not be implemented in this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54)

### CODE REVIEW

**Review by qhz-ty — CHANGES_REQUESTED** [review]
> Reviewed 48 of 48 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54)* status: all files reviewed, 6 unresolved discussions (waiting on @k-huetsch, @MetaJuniper, and @zz-ionian)

___
*[`common/append_merkle/src/proof.rs` line 15 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA4AuAg6_sW0K_3UbPr:-NA4AuAg6_sW0K_3UbPs:bjnog74) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/common/append_merkle/src/proof.rs#L15)):*
> ```XML
>     /// Creates new MT inclusion proof
>     pub fn new(hash: Vec<T>, path: Vec<bool>) -> Proof<T> {
>         assert_eq!(hash.len() - 2, path.len());
> ```

What about a single root node case?
___
*[`common/append_merkle/src/proof.rs` line 19 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA4A1kN92XKHQ5CiAlp:-NA4A1kN92XKHQ5CiAlq:boawt46) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/common/append_merkle/src/proof.rs#L19)):*
> ```XML
>     }
> 
>     pub fn new_empty() -> Proof<T> {
> ```

How about to remove this constructor to avoid `unwrap` panics in `item` and `root` methods?
___
*[`common/append_merkle/src/proof.rs` line 37 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA4BPJ5Ds00Ii30R0yA:-NA4BPJ5Ds00Ii30R0yB:bfpzzlt) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/common/append_merkle/src/proof.rs#L37)):*
> ```XML
> 
>     /// Verifies MT inclusion proof
>     pub fn validate_integrity<A: Algorithm<T>>(&self) -> bool {
> ```

Suggest to return `Result<()>` for all `validate_xxx` methods to keep consistency.
___
*[`common/append_merkle/src/proof.rs` line 66 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA4Bp7sCdUN9uB5iKvC:-NA4Bp7sCdUN9uB5iKvD:bgy7w6a) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/common/append_merkle/src/proof.rs#L66)):*
> ```XML
>             bail!("Proof position unmatch");
>         }
>         Ok(())
> ```

Is it necessary to check if `root` matched?
___
*[`node/router/src/service.rs` line 86 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA44zLb1XikWJwskVKZ:-NA44zLb1XikWJwskVK_:b-yli3ae) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/node/router/src/service.rs#L86)):*
> ```XML
>         sync_send: SyncSender,
>         miner_send: mpsc::UnboundedSender<MinerMessage>,
>         store: Arc<RwLock<dyn LogStore>>,
> ```

Data type of `store` changed to `RwLock`, but `store.read/write` not found in this file, is it as expected? 



_Code quote:_
```XML
store: Arc<RwLock<dyn LogStore>>
```
___
*[`node/shared_types/src/lib.rs` line 39 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA45cp4D24gZx-jC9i1:-NA45cp4D24gZx-jC9i2:bjszcy4) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/node/shared_types/src/lib.rs#L39)):*
> ```XML
> #[serde(rename_all = "camelCase")]
> pub struct Transaction {
>     pub stream_ids: Vec<U256>,
> ```

Not found in `Flow` contract, remove it? Please also check other fields, e.g. `data`, `size`.



_Code quote:_
```XML
stream_ids
```

**Review by loganionion — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54)* status: all files reviewed, 6 unresolved discussions (waiting on @k-huetsch, @MetaJuniper, and @zz-ionian)

**Review by zz-ionian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54)* status: 47 of 48 files reviewed, 6 unresolved discussions (waiting on @k-huetsch, @MetaJuniper, and @qhz-ty)

___
*[`common/append_merkle/src/proof.rs` line 15 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA4AuAg6_sW0K_3UbPr:-NA89JUH4K_d0GcDZvo-:b-dhji4h) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/common/append_merkle/src/proof.rs#L15)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

What about a single root node case?
</blockquote></details>

For flow-based proof, `self.lemma` is defined as `[root, root]` for simplicity. And probably we can use the same method for file-based proofs. File proofs are not changed for compatibility.
___
*[`common/append_merkle/src/proof.rs` line 19 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA4A1kN92XKHQ5CiAlp:-NA8A3Ko5Ew2tnfqNFOu:bp79z7n) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/common/append_merkle/src/proof.rs#L19)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

How about to remove this constructor to avoid `unwrap` panics in `item` and `root` methods?
</blockquote></details>

This is only used for computing the min/max size of p2p messages, and it's not really accurate since empty proofs are invalid. It can be removed later when that limit is computed differently.
___
*[`common/append_merkle/src/proof.rs` line 37 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA4BPJ5Ds00Ii30R0yA:-NA8AgGZ9kNaIbRM2fFt:b-ciakyu) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/common/append_merkle/src/proof.rs#L37)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

Suggest to return `Result<()>` for all `validate_xxx` methods to keep consistency.
</blockquote></details>

This is only used internally. I've removed `pub`.
___
*[`common/append_merkle/src/proof.rs` line 66 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA4Bp7sCdUN9uB5iKvC:-NA8AqxP77ZtiG79HHCr:b7l2k3p) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/common/append_merkle/src/proof.rs#L66)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

Is it necessary to check if `root` matched?
</blockquote></details>

The `root` of the global flow is always changing, so there is no specific root to check against... It's checked in `LogManager` whether the root of the proof is valid (just check if it exists).
___
*[`node/router/src/service.rs` line 86 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA44zLb1XikWJwskVKZ:-NA8BQURBv809m5i_yLw:bwn8wsa) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/node/router/src/service.rs#L86)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

Data type of `store` changed to `RwLock`, but `store.read/write` not found in this file, is it as expected? 
</blockquote></details>

Currently `write` is only called within `storage-async` and we use `write` even for read-only operations... This lock here is just added as a temporary solution. We'll need to decide if it's needed when all usages are stabilized.
___
*[`node/shared_types/src/lib.rs` line 39 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54#-NA45cp4D24gZx-jC9i1:-NA8C16FAs7kZyQE6FQW:b-tp1weq) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/cfe81fe6d5bb5669fe9f88c1e61beb3008c9e550/node/shared_types/src/lib.rs#L39)):*
<details><summary><i>Previously, qhz-ty wrote…</i></summary><blockquote>

Not found in `Flow` contract, remove it? Please also check other fields, e.g. `data`, `size`.
</blockquote></details>

The discussion mentions that we may want to store `stream_ids` in another contract. I guess in the storage node we can save all information of a file together in one struct. After the contract is stabilized, we can move it to another struct if it's more efficient, or remove it if it's not needed at all.

**Review by qhz-ty — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @k-huetsch and @MetaJuniper)

**Pull request merged**
