### PR TITLE
Add test for sync crate

### PR DESCRIPTION
**Pull request by cxlup**
Add test for sync crate

- - -
This change is [Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/68)

### CODE REVIEW

**Review by zz-ionian — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/68)* status: all files reviewed, 1 unresolved discussion (waiting on @cxlup)

___
*[`node/sync/src/service.rs` line 523 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/68#-N9osaeV8O0qCMmB11Jx:-N9osaeV8O0qCMmB11Jy:be2akpc) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/f4ffd6632baa20749752fce6cc9a5a0ddc21a4fc/node/sync/src/service.rs#L523)):*
> ```XML
>             .unwrap();
> 
>         if let Some(msg) = network_recv.recv().await {
> ```

`recv` returning `None` here should also be an error. Same for other similar tests.

Actually it might be clearer to write this as `assert!(matches!(network_recv.recv().await, ...))` or `assert_eq!(network_recv.recv().await, ...))`.

**Comment by cxlup** [comment]
*[`node/sync/src/service.rs` line 523 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/68#-N9osaeV8O0qCMmB11Jx:-N9pH1R0EMk_wMxATEZB:bcfw6rs) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/f4ffd6632baa20749752fce6cc9a5a0ddc21a4fc/node/sync/src/service.rs#L523)):*
<details><summary><i>Previously, zz-ionian wrote…</i></summary><blockquote>

`recv` returning `None` here should also be an error. Same for other similar tests.

Actually it might be clearer to write this as `assert!(matches!(network_recv.recv().await, ...))` or `assert_eq!(network_recv.recv().await, ...))`.
</blockquote></details>

To use assert, we need mark related types (NetworkMessage and sub types) derive Eq/PartialEq, most these types are from network module (from lighthouse), can we make these changes?

**Review by zz-ionian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/68)* status: all files reviewed, 1 unresolved discussion (waiting on @cxlup)

___
*[`node/sync/src/service.rs` line 523 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/68#-N9osaeV8O0qCMmB11Jx:-N9pLoyu6qJHnbAU5hQ3:b-dlh8r3) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/f4ffd6632baa20749752fce6cc9a5a0ddc21a4fc/node/sync/src/service.rs#L523)):*
<details><summary><i>Previously, cxlup (csd) wrote…</i></summary><blockquote>

To use assert, we need mark related types (NetworkMessage and sub types) derive Eq/PartialEq, most these types are from network module (from lighthouse), can we make these changes?
</blockquote></details>

Okay... I feel this should be okay. It would be better if they are only derived for tests but I do not know if that's possible.

**Review by zz-ionian — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/68)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cxlup)

**Pull request merged**
