### PR TITLE
Add exit code for framework

### PR DESCRIPTION
**Pull request by cxlup**
Add exit code for framework
Remove assert in __init__

- - -
This change is [Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/69)

### CODE REVIEW

**Review by zz-ionian — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/69)* status: all files reviewed, 1 unresolved discussion (waiting on @cxlup and @qhz-ty)

___
*[`tests/test_framework/test_framework.py` line 33 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/69#-NA3MoS-9LbW48kvrToj:-NA3MoS-9LbW48kvrTok:b-c5iz0g) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/eaa252fc2c841befd20fe711b427bec7ba587777/tests/test_framework/test_framework.py#L33)):*
> ```Python
> TEST_EXIT_PASSED = 0
> TEST_EXIT_FAILED = 1
> TEST_EXIT_SKIPPED = 77
> ```

The skip exception and status are not used in the test framework yet?

**Comment by cxlup** [comment]
*[`tests/test_framework/test_framework.py` line 33 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/69#-NA3MoS-9LbW48kvrToj:-NA3aesTApVTmS4mz0dv:bpxuo5m) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/eaa252fc2c841befd20fe711b427bec7ba587777/tests/test_framework/test_framework.py#L33)):*
<details><summary><i>Previously, zz-ionian wrote…</i></summary><blockquote>

The skip exception and status are not used in the test framework yet?
</blockquote></details>

Yes, I leave it here in case we can use it in future, should I remove it？

**Review by zz-ionian — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/69)* status: all files reviewed, 1 unresolved discussion (waiting on @cxlup and @qhz-ty)

___
*[`tests/test_framework/test_framework.py` line 33 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/69#-NA3MoS-9LbW48kvrToj:-NA3bQUk7QWmoCWj1ZhP:b-1f4inw) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/eaa252fc2c841befd20fe711b427bec7ba587777/tests/test_framework/test_framework.py#L33)):*
<details><summary><i>Previously, cxlup (csd) wrote…</i></summary><blockquote>

Yes, I leave it here in case we can use it in future, should I remove it？
</blockquote></details>

I'm actually not sure when it will be used... We can keep it if you have some idea, otherwise, I guess we can remove it.

**Comment by cxlup** [comment]
*[`tests/test_framework/test_framework.py` line 33 at r1](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/69#-NA3MoS-9LbW48kvrToj:-NA7Om1S4sI-WzmpiOR0:bmz5ckf) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/eaa252fc2c841befd20fe711b427bec7ba587777/tests/test_framework/test_framework.py#L33)):*
<details><summary><i>Previously, zz-ionian wrote…</i></summary><blockquote>

I'm actually not sure when it will be used... We can keep it if you have some idea, otherwise, I guess we can remove it.
</blockquote></details>

Removed the Skip status

**Review by zz-ionian — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @qhz-ty)

**Pull request merged**
