### PR TITLE
Enable mining proof verification.

### PR DESCRIPTION
**Pull request by zz-ionian**
This change is [Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/106)

### CODE REVIEW

**Comment by zz-ionian** [comment]
The miner currently uses the local latest flow root to generate the proof. This will be changed to use the flow root in the mining context in the following PR.

**Review by qhz-ty — DISMISSED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @k-huetsch)

**Review by k-huetsch — CHANGES_REQUESTED** [review]
> Reviewed 14 of 27 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/106)* status: 26 of 28 files reviewed, 1 unresolved discussion (waiting on @qhz-ty and @zz-ionian)

___
*[`node/miner/src/pora.rs` line 72 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/106#-NCcIWjr4bHOLH_UoUIJ:-NCcIWjr4bHOLH_UoUIK:bk4aw43) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ec439ce3ea4ffb0db509c8d10e2dec6327c85f9e/node/miner/src/pora.rs#L72)):*
> ```XML
>             .unwrap()
>         {
>             info!(
> ```

Unavailable recall position could happen frequently. Don't put a log here.

**Review by k-huetsch — COMMENTED** [review]
> Reviewed 7 of 27 files at r1, 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/106)* status: all files reviewed, 1 unresolved discussion (waiting on @zz-ionian)

**Review by zz-ionian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/106)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @k-huetsch and @qhz-ty)

___
*[`node/miner/src/pora.rs` line 72 at r2](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/106#-NCcIWjr4bHOLH_UoUIJ:-NCcLbAP2o0I552DLOZ8:b-896fix) ([raw file](https://github.com/ionian-web3-storage/ionian-rust/blob/ec439ce3ea4ffb0db509c8d10e2dec6327c85f9e/node/miner/src/pora.rs#L72)):*
<details><summary><i>Previously, k-huetsch (Kevin Huetsch) wrote…</i></summary><blockquote>

Unavailable recall position could happen frequently. Don't put a log here.
</blockquote></details>

Done.

**Review by k-huetsch — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ionian-web3-storage/ionian-rust/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zz-ionian)

**Pull request merged**
